name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Stdin Stdout Test
      id: stdin-stdout-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Stdin Stdout Test
        setup-command: "./setup.sh"
        command: gradle test
        timeout: 3
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        STDIN-STDOUT-TEST_RESULTS: "${{steps.stdin-stdout-test.outputs.result}}"
      with:
        runners: stdin-stdout-test
